"""empty message

Revision ID: 44e4335644fd
Revises: ae6cc91cf996
Create Date: 2025-12-22 23:01:04.974879

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44e4335644fd'
down_revision: Union[str, Sequence[str], None] = 'ae6cc91cf996'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gamesession', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_gamesession_status'), 'gamesession', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gamesession_status'), table_name='gamesession')
    op.drop_column('gamesession', 'status')
    # ### end Alembic commands ###
