"""empty message

Revision ID: 7404d5183a5a
Revises:
Create Date: 2025-11-14 16:40:02.045817

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7404d5183a5a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("victories", sa.Integer(), nullable=False))
    op.add_column("user", sa.Column("defeats", sa.Integer(), nullable=False))
    op.drop_column("user", "points")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("points", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.drop_column("user", "defeats")
    op.drop_column("user", "victories")
    # ### end Alembic commands ###
