"""empty message

Revision ID: ae6cc91cf996
Revises: dadb25ce52d4
Create Date: 2025-12-03 01:18:59.523792

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ae6cc91cf996"
down_revision: Union[str, Sequence[str], None] = "dadb25ce52d4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gamesession",
        sa.Column("game_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.drop_column("gamesession", "game_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gamesession",
        sa.Column("game_name", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("gamesession", "game_type")
    # ### end Alembic commands ###
