"""empty message

Revision ID: d2e9d623adef
Revises: 7404d5183a5a
Create Date: 2025-11-15 13:50:19.744130

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d2e9d623adef"
down_revision: Union[str, Sequence[str], None] = "7404d5183a5a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_gamesession_game_id"), table_name="gamesession")
    op.drop_table("gamesession")
    op.drop_table("wordlist")
    op.drop_table("gametype")
    op.drop_index(op.f("ix_user_identifier"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('user_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("identifier", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("mail", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("points", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="user_pkey"),
        sa.UniqueConstraint(
            "mail",
            name="user_mail_key",
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        postgresql_ignore_search_path=False,
    )
    op.create_index(op.f("ix_user_identifier"), "user", ["identifier"], unique=True)
    op.create_table(
        "gametype",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('gametype_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="gametype_pkey"),
        sa.UniqueConstraint(
            "type",
            name="gametype_type_key",
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "wordlist",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "words", postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("wordlist_pkey")),
        sa.UniqueConstraint(
            "name",
            name=op.f("wordlist_name_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "gamesession",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("game_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("game_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "gameData",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "player1_identifier", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "player2_identifier", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "waiting",
                "ready",
                "active",
                "paused",
                "timeout",
                "finished",
                "abandoned",
                name="status",
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["game_type"], ["gametype.type"], name=op.f("gamesession_game_type_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["player1_identifier"],
            ["user.identifier"],
            name=op.f("gamesession_player1_identifier_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["player2_identifier"],
            ["user.identifier"],
            name=op.f("gamesession_player2_identifier_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("gamesession_pkey")),
    )
    op.create_index(
        op.f("ix_gamesession_game_id"), "gamesession", ["game_id"], unique=True
    )
    # ### end Alembic commands ###
