"""empty message

Revision ID: dadb25ce52d4
Revises: f5fd990d8dac
Create Date: 2025-12-03 00:23:01.242057

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dadb25ce52d4"
down_revision: Union[str, Sequence[str], None] = "f5fd990d8dac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gamesession",
        sa.Column("winner_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.alter_column(
        "gamesession", "game_name", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "gamesession",
        "game_data",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=True,
    )
    op.drop_column("gamesession", "status")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gamesession",
        sa.Column(
            "status",
            postgresql.ENUM(
                "waiting",
                "ready",
                "active",
                "paused",
                "timeout",
                "finished",
                "abandoned",
                name="status",
            ),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.alter_column(
        "gamesession",
        "game_data",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "gamesession", "game_name", existing_type=sa.VARCHAR(), nullable=True
    )
    op.drop_column("gamesession", "winner_id")
    # ### end Alembic commands ###
