"""empty message

Revision ID: eb39829ff610
Revises: c04ca025e988
Create Date: 2025-11-21 13:11:29.051202

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb39829ff610'
down_revision: Union[str, Sequence[str], None] = 'c04ca025e988'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('gamesession_game_type_fkey'), 'gamesession', type_='foreignkey')
    op.drop_table('gametype')
    op.add_column('gamesession', sa.Column('game_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('gamesession', 'game_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gamesession', sa.Column('game_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('gamesession_game_type_fkey'), 'gamesession', 'gametype', ['game_type'], ['type'])
    op.drop_column('gamesession', 'game_name')
    op.create_table('gametype',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('gametype_pkey')),
    sa.UniqueConstraint('type', name=op.f('gametype_type_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
