"""empty message

Revision ID: f5b6ca87367a
Revises: c3a991a3859c
Create Date: 2025-11-17 22:46:12.759962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5b6ca87367a'
down_revision: Union[str, Sequence[str], None] = 'c3a991a3859c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wordlist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wordlist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('words', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('wordlist_pkey')),
    sa.UniqueConstraint('name', name=op.f('wordlist_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
