"""empty message

Revision ID: fae3ff70807b
Revises: 32626a6bd1b5
Create Date: 2025-11-17 20:55:15.799441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fae3ff70807b'
down_revision: Union[str, Sequence[str], None] = '32626a6bd1b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gamesession', sa.Column('game_data', sa.JSON(), nullable=False))
    op.drop_column('gamesession', 'gameData')
    op.add_column('user', sa.Column('victories', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('defeats', sa.Integer(), nullable=False))
    op.drop_column('user', 'points')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wordlist', 'words',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=False)
    op.add_column('user', sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('user', 'defeats')
    op.drop_column('user', 'victories')
    op.add_column('gamesession', sa.Column('gameData', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('gamesession', 'game_data')
    # ### end Alembic commands ###
